### ISSUE TITLE
site_policies issue -- You are not authorized to call this agent or action

### ISSUE THREAD

**Issue by pre-srn** [choria-io/vagrant-demo#1]
Hi,

I came across this and have tried it for a few days. I found that the site policies hiera config doesn't allow to call any puppet agent.
```
mcollective::site_policies:
  - action: "allow"
    callers: "choria=vagrant.mcollective"
    actions: "*"
    facts: "*"
    classes: "*"
```
The agents responded as `You are not authorized to call this agent or action` when testing with `mco puppet status`

So, I tried to test with the default allow policies `mcollective_agent_puppet::policy_default: allow` and this time I could call all agents.

Note that I have investigated the following (which looks correct to me). 
- The vagrant.mcollective certificate was signed correctly --> checked with `puppet cert list --all`
- The vagrant.mcollective cert has been rolled out to all agents already.
I'm not sure what is wrong here as I'm very new to puppet and mcollective. Please let me know if there is a way to make it work.

Also, if I perform a clean install this manually on my machince, will it work for me?

**Comment by ripienaar** [comment]
If you install using the guide on choria.io yes, it will work, considering guidance here about AAA https://choria.io/docs/configuration/aaa/

This here setup seems fine, but I'll test and fix if there is a bug.

**Comment by ripienaar** [comment]
I've tried various ways to replicate this problem and failed, several rebuilds and so it just works fine.

I'm going to be closing this, as far as I can tell it works a charm.

**Comment by pre-srn** [comment]
Sorry for bothering. I still couldn't make it work for me. I don't know why. 
I just simply requested the cert after performing "vagrant up" and tried to call the agent but they still responded as " You are not authorized to call this agent or action."

Am I doing anything incorrectly based on this vagrant setup?

**Comment by ripienaar** [comment]
clearly something is wrong, do you mind copy and pasting the full output from the point where you `vagrant ssh puppet` till the error?

**Comment by pre-srn** [comment]
Hi. Here is the output. As you can see, each agent responded as "You are not authorized to call this agent or action.". 

```
[vagrant@puppet ~]$ whoami
vagrant
[vagrant@puppet ~]$ mco choria request_cert
Requesting certificate for '/home/vagrant/.puppetlabs/etc/puppet/ssl/certs/vagrant.mcollective.pem'
Waiting up to 240 seconds for it to be signed

Attempting to download certificate /home/vagrant/.puppetlabs/etc/puppet/ssl/certs/vagrant.mcollective.pem: 0 /Certificate /home/vagrant/.puppetlabs/etc/puppet/ssl/certs/vagrant.mcollective.pem has been stored in /home/vagrant/.puppetlabs/etc/puppet/ssl
[vagrant@puppet ~]$ mco ping
puppet.choria                            time=47.43 ms
choria1.choria                           time=49.30 ms
choria0.choria                           time=51.11 ms


---- ping statistics ----
3 replies max: 51.11 min: 47.43 avg: 49.28
[vagrant@puppet ~]$ mco puppet status

 * [ ============================================================> ] 3 / 3

   choria1.choria: You are not authorized to call this agent or action.
    puppet.choria: You are not authorized to call this agent or action.
   choria0.choria: You are not authorized to call this agent or action.

Summary of Applying:

   false = 3

Summary of Daemon Running:

   stopped = 3

Summary of Enabled:

     No aggregate summary could be computed

Summary of Idling:

   false = 3

Summary of Status:

   unknown = 3


Finished processing 3 / 3 hosts in 23.56 ms

[vagrant@puppet ~]$
```

**Comment by ripienaar** [comment]
And `mco rpc rpcutil ping`?

Can you include a log from one of these denying it?

**Comment by ripienaar** [comment]
And you are on the latest checkout of the repo yeah?

**Comment by pre-srn** [comment]
Yep, I'm on the lates checkout.
And the `mco rpc rpcutil ping` command gets denied as well.
I'm using Windows, not sure whether it is the case or not. Anyway, I'm going to try with Linux.

```
[vagrant@puppet ~]$ mco rpc rpcutil ping
Discovering hosts using the mc method for 2 second(s) .... 3

 * [ ============================================================> ] 3 / 3


puppet.choria                            Request Aborted
   You are not authorized to call this agent or action.

choria0.choria                           Request Aborted
   You are not authorized to call this agent or action.

choria1.choria                           Request Aborted
   You are not authorized to call this agent or action.



Finished processing 3 / 3 hosts in 16.26 ms
```

**Comment by ripienaar** [comment]
it shouldnt, can you show the log?

**Comment by pre-srn** [comment]
Do you mean the vagrant log?

**Comment by ripienaar** [comment]
from one of the nodes thats denying the requests.

All your nodes should have files like this:

```
$ cat /etc/puppetlabs/mcollective/policies/rpcutil.policy
policy default deny

# rpcutil module specific policies
allow	*	ping	*	*

# site wide policies
allow	choria=vagrant.mcollective	*	*	*
```

Else I suspect the puppet run is giving errors, you can check with running `/opt/puppetlabs/bin/puppet agent --test` and check the output for errors if this file isnt there

**Comment by pre-srn** [comment]
The file is there. However, when I ran `/opt/puppetlabs/bin/puppet agent --test` without `sudo` I got the following error, but running it with `sudo` was fine.
```
[vagrant@puppet ~]$ /opt/puppetlabs/bin/puppet agent --test
Error: Could not request certificate: The certificate retrieved from the master does not match the agent's private key. Did you forget to run as root?
Certificate fingerprint: EA:B0:B3:32:51:CA:11:CB:F0:B2:69:1E:86:80:2A:0B:31:35:DB:C9:7B:92:1F:EF:95:42:12:B1:E6:B0:75:2C
To fix this, remove the certificate from both the master and the agent and then start a puppet run, which will automatically regenerate a certificate.
On the master:
  puppet cert clean puppet.choria
On the agent:
  1a. On most platforms: find /home/vagrant/.puppetlabs/etc/puppet/ssl -name puppet.choria.pem -delete
  1b. On Windows: del "\home\vagrant\.puppetlabs\etc\puppet\ssl\certs\puppet.choria.pem" /f
  2. puppet agent -t

Exiting; failed to retrieve certificate and waitforcert is disabled
[vagrant@puppet ~]$ sudo /opt/puppetlabs/bin/puppet agent --test
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for puppet.choria
Info: Applying configuration version '1531265639'
Notice: Applied catalog in 5.11 seconds
```
Is this the cause?

**Comment by ripienaar** [comment]
Need to run with sudo sorry I wasn’t clear. What happens with sudo?

**Comment by ripienaar** [comment]
sudo is required. So that looks fine. Please show the mcollective log I requested

**Comment by pre-srn** [comment]
Here is the full log file.
[mcollective.log](https://github.com/choria-io/vagrant-demo/files/2184140/mcollective.log)

**Comment by ripienaar** [comment]
this all seems fine, am a bit out of ideas, can you edit the server.cfg like this:

```
$ sudo /opt/puppetlabs/bin/puppet agent --disable
$ sudo vi /etc/puppetlabs/mcollective/server.cfg
loglevel=debug
$ sudo service mcollective restart
``

Then do rpc request again and show me the log again?

**Comment by pre-srn** [comment]
Yep, I have no ideas as well. Here is the log. The rpc request started at 11:48:54.
[mcollective.log](https://github.com/choria-io/vagrant-demo/files/2184311/mcollective.log)

**Comment by ripienaar** [comment]
ok, please show `/etc/puppetlabs/mcollective/policies/puppet.policy`

**Comment by pre-srn** [comment]
Ok. Here it is.
```
[vagrant@puppet ~]$ cat /etc/puppetlabs/mcollective/policies/puppet.policy
policy default deny

# mcollective_agent_puppet module specific policies
allow   *       last_run_summary status *       *

# site wide policies
allow   choria=vagrant.mcollective      *       *       *
```

**Comment by ripienaar** [comment]
I can noly assume this file is corrupt somehow, action policy isnt that great at reporting this.

please send output of `base64 /etc/puppetlabs/mcollective/policies/puppet.policy`

**Comment by pre-srn** [comment]
The base64 is as follows 
```
cG9saWN5IGRlZmF1bHQgZGVueQ0KDQojIG1jb2xsZWN0aXZlX2FnZW50X3B1cHBldCBtb2R1bGUgc3BlY2lmaWMgcG9saWNpZXMNCmFsbG93CSoJbGFzdF9ydW5fc3VtbWFyeSBzdGF0dXMJKgkqDQoNCiMgc2l0ZSB3aWRlIHBvbGljaWVzDQphbGxvdwljaG9yaWE9dmFncmFudC5tY29sbGVjdGl2ZQkqCSoJKg0K
```

**Comment by ripienaar** [comment]
this seems fine too, tbh i am out of idea.

Unless you are open to start a zoom session with me where I can type on this vagrant instance I dont know :)

**Comment by pre-srn** [comment]
Sorry, I am not available to do that now. Anyway, I will try this on other machaines.

**Comment by ripienaar** [comment]
likewise, but we can schedule something for later if you want

**Comment by pre-srn** [comment]
Yep can I contact you via email?

**Comment by ripienaar** [comment]
sure, rip@devco.net

**Comment by pre-srn** [comment]
For an unknown reason, it works like a charm on Linux (Ubuntu latest version)!

**Comment by ripienaar** [comment]
ah, I get it, your git checkout converted the line endings - now that I look again at the base64 file thats exactly the problem.

the puppet template in the repo effectively got corrupted.

`git config core.autocrlf false` probably fixes it on windows, I can add a file `.gitattributes` here to configure your git for you, will have a play with that

**Comment by pre-srn** [comment]
Okay, I see. Thanks for all your help :)

**Comment by ripienaar** [comment]
I've put a file that should configure your git to not break things, do you mind doing a fresh checkout after deleting your existing one and testing again on windows @presoranut ?

**Comment by pre-srn** [comment]
Tested. It's working perfectly fine.

**Comment by ripienaar** [comment]
excellent, learnt something new!

thanks for sticking with it, I know it was a lot of wasted time
